workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          pod install --project-directory=ios
      - name: Run tests
        script: |
          flutter test
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CI_WORKSPACE/build/Runner.xcarchive
          xcodebuild -exportArchive -archivePath $CI_WORKSPACE/build/Runner.xcarchive -exportPath $CI_WORKSPACE/build -exportOptionsPlist ios/ExportOptions.plist
    artifacts:
      - build/Runner.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
