workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      node: latest
      vars:
        # Add your environment variables here, for example:
        # - name: APP_STORE_CONNECT_PRIVATE_KEY
        #   value: Encrypted(...) # Encrypt sensitive values in the UI

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Export IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/Runner.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath $CM_BUILD_DIR/IPA

    artifacts:
      - $CM_BUILD_DIR/IPA/*.ipa
      - $CM_BUILD_DIR/Runner.xcarchive
