workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "YourProject.xcworkspace"
        XCODE_SCHEME: "YourProject"
        XCODE_PROJECT: "YourProject.xcodeproj"
    scripts:
      - name: Set up the environment
        script: |
          echo "Setting up environment"
      - name: Check Xcode version
        script: |
          xcodebuild -version
      - name: Clean and reset derived data
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Install dependencies
        script: |
          brew update
          brew install cocoapods
          pod install
      - name: Disable module interface generation
        script: |
          defaults write com.apple.dt.Xcode IDEIndexDisable 1
          defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks 1
      - name: Clean the build folder
        script: |
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release
      - name: Build the project
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
